[General]
# background=#0a0a0a  |  background=background.jpg  |  background=/usr/share/backgrounds/default.jpg
# TokyoNight Night #1a1b26 / Storm #24283b / Moon #222436
background=#13282b

# date / clock
showDate=true
dateFormat=dddd dd/MM/yyyy
showClock=true
clock12hr=true
clockSeconds=true

# box
hideBorders=false
boxBackground=true
boxBackgroundColor=#233b3f

# function key,
# show do not disable key, just not showing it
showShutdownKey=true
shutdownKey=F1
showRebootKey=true
rebootKey=F2
showPasswordToggleKey=true
passwordToggleKey=F7

# font
fontFamily=
fontSize=15
boxFontSize=15

# primaryScreen: empty=show on all (default) | eDP-1/HDMI-A-1=only that output (exact, case-sensitive), unknown falls back to system primary screen
primaryScreen=

# session / user / password
defaultInput=password

# input length (box width based on inputLen)
inputLen=20

# default show nothing,linux style, this echoes * per character
asterisk=*